### ISSUE TITLE
Remove #!/bin/bash

### ISSUE THREAD

**Issue by gnurenga** [nithyaraman/pythontraining#2]
Why you used #!/bin/bash ?

**Comment by nithyaraman** [comment]
i removed that ...while write program in svn everybody write like that so i thought this is a format to write like that

**Comment by gnurenga** [comment]
* What is the purpose of using #!/bin/bash ?
Kindly read about it. Git and SVN are just a version control management softwares. 
In which program they used #!/bin/bash while you used SVN ?

**Comment by nithyaraman** [comment]
okay ,while writing shell script i mention #!/bin/bash . Now i come to know ,"script  should always run with bash rather then another shell means need to mention this  #!/bin/bash or else no need".
